export const kinesis = `// This Kinesis Stream Template has been generated by serverless-rebar
use aws_lambda_events::event::kinesis::{KinesisEvent};
use lambda_runtime::{handler_fn, Context};

type Error = Box<dyn std::error::Error + Sync + Send + 'static>;

async fn {{name}}_handler(event: KinesisEvent, _: Context) -> Result<(), Error> {
    Ok(())
}

#[tokio::main]
async fn main() -> Result<(), Error> {
    let func = handler_fn({{name}}_handler);
    lambda_runtime::run(func).await?;
    Ok(())
}`
